"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.PURPLE_GRADIENT = exports.RED_GRADIENT = exports.BROWN_GRADIENT = exports.GRAY_GRADIENT = exports.BLUE_GRADIENT = exports.YELLOW_GRADIENT = exports.DARK_BLUE = exports.LIGHT_BLUE = exports.DARK_GREEN = exports.LIGHT_GREEN = exports.RED = exports.DARK_GRAY = exports.GRAY = exports.WHITE = exports.BLACK = void 0;
exports.BLACK = '#222222';
exports.WHITE = '#FFFFFF';
exports.GRAY = '#DCDCDC';
exports.DARK_GRAY = '#666666';
exports.RED = '#F54545';
exports.LIGHT_GREEN = '#14D49B';
exports.DARK_GREEN = '#004E53';
exports.LIGHT_BLUE = '#3478F6';
exports.DARK_BLUE = '#00407C';
exports.YELLOW_GRADIENT = ['#FFF500', '#D6CD00'];
exports.BLUE_GRADIENT = ['#2C9AFF', '#1A5C99'];
exports.GRAY_GRADIENT = ['#C9C9C9', '#636363'];
exports.BROWN_GRADIENT = ['#DB5C00', '#753100'];
exports.RED_GRADIENT = ['#FF2C2C', '#991A1A'];
exports.PURPLE_GRADIENT = ['#D484E8', '#442061'];
