"use strict";
var _a;
Object.defineProperty(exports, "__esModule", { value: true });
exports.problemCausesForCategories = void 0;
var types_1 = require("../types");
exports.problemCausesForCategories = (_a = {},
    _a[types_1.Category.DRY_SOILS] = [
        'Lack of rainfall',
        'High temperatures',
        'Poor soil structure',
        'Overuse of water resources',
        'Deforestation',
        'Climate change',
        'Overgrazing',
        'Other',
    ],
    _a[types_1.Category.WET_SOILS] = [
        'Heavy rainfall',
        'Poor drainage systems',
        'High water table',
        'Over-irrigation',
        'Soil compaction',
        'Urbanization',
        'Flooding',
        'Other',
    ],
    _a[types_1.Category.EROSION] = [
        'Wind erosion',
        'Water erosion',
        'Human activity',
        'Gully erosion',
        'Sheet erosion',
        'Rill erosion',
        'Other',
    ],
    _a[types_1.Category.SEALED_SOILS] = [
        'Urbanization',
        'Agricultural practices',
        'Industrial activities',
        'Soil compaction',
        'Paving and concreting',
        'Natural processes',
        'Other',
    ],
    _a[types_1.Category.DEGRADATION] = [
        'Erosion',
        'Contamination',
        'Loss of nutrients',
        'Overuse of soil',
        'Deforestation',
        'Climate change',
        'Overgrazing',
        'Other',
    ],
    _a[types_1.Category.LOSS_OF_ORGANIC_MATTER] = [
        'Intensive agriculture',
        'Deforestation',
        'Overgrazing',
        'Soil erosion',
        'Climate change',
        'Poor land management',
        'Other',
    ],
    _a[types_1.Category.PH] = [
        'Acidic',
        'Slightly acidic',
        'Neutral',
        'Slightly alkaline',
        'Alkaline',
        'Not sure',
        'Other',
    ],
    _a[types_1.Category.BIODIVERSITY] = [
        'Agricultural practices',
        'Urbanization',
        'Pollution',
        'Climate change',
        'Deforestation',
        'Natural soil conditions',
        'Other',
    ],
    _a);
