import { Category } from '../types';

export const problemCausesForCategories: Record<Category, string[]> = {
  [Category.DRY_SOILS]: [
    'Lack of rainfall',
    'High temperatures',
    'Poor soil structure',
    'Overuse of water resources',
    'Deforestation',
    'Climate change',
    'Overgrazing',
    'Other',
  ],
  [Category.WET_SOILS]: [
    'Heavy rainfall',
    'Poor drainage systems',
    'High water table',
    'Over-irrigation',
    'Soil compaction',
    'Urbanization',
    'Flooding',
    'Other',
  ],
  [Category.EROSION]: [
    'Wind erosion',
    'Water erosion',
    'Human activity',
    'Gully erosion',
    'Sheet erosion',
    'Rill erosion',
    'Other',
  ],
  [Category.SEALED_SOILS]: [
    'Urbanization',
    'Agricultural practices',
    'Industrial activities',
    'Soil compaction',
    'Paving and concreting',
    'Natural processes',
    'Other',
  ],
  [Category.DEGRADATION]: [
    'Erosion',
    'Contamination',
    'Loss of nutrients',
    'Overuse of soil',
    'Deforestation',
    'Climate change',
    'Overgrazing',
    'Other',
  ],
  [Category.LOSS_OF_ORGANIC_MATTER]: [
    'Intensive agriculture',
    'Deforestation',
    'Overgrazing',
    'Soil erosion',
    'Climate change',
    'Poor land management',
    'Other',
  ],
  [Category.PH]: [
    'Acidic',
    'Slightly acidic',
    'Neutral',
    'Slightly alkaline',
    'Alkaline',
    'Not sure',
    'Other',
  ],
  [Category.BIODIVERSITY]: [
    'Agricultural practices',
    'Urbanization',
    'Pollution',
    'Climate change',
    'Deforestation',
    'Natural soil conditions',
    'Other',
  ],
};
