import { Category } from '../types';

export const problemCausesForCategories: Record<Category, string[]> = {
  [Category.DRY_SOILS]: [
    'Lack of rainfall (Periods of little or no rain)',
    'High temperatures (Hot weather causing evaporation)',
    'Poor soil structure (Soil that doesn’t retain water well)',
    'Overuse of water resources (Excessive use of water for agriculture or other purposes)',
    'Deforestation (Removal of trees that help retain moisture)',
    'Climate change (Long-term changes in weather patterns)',
    'Overgrazing (Excessive grazing by livestock)',
    'Other',
  ],
  [Category.WET_SOILS]: [
    'Heavy rainfall (Frequent or intense rain)',
    'Poor drainage systems (Inadequate drainage infrastructure)',
    'High water table (Groundwater level close to the surface)',
    'Over-irrigation (Excessive watering of crops or gardens)',
    'Soil compaction (Soil particles pressed together, reducing pore space)',
    'Urbanization (Increased impermeable surfaces like roads and buildings)',
    'Flooding (Overflow of water from rivers or lakes)',
    'Other',
  ],
  [Category.EROSION]: [
    'Water (rills, inter-rill, gully, snowmelt, and river and lake bank erosion)',
    'Wind (desiccation and wind-blow)',
    'Translocation (tillage, land leveling, harvesting of root crops, trampling, and burrowing animals)',
    'Geological (internal subterranean erosion by groundwater, coastal erosion, and landslides)',
    'Poor land management such as overgrazing, deforestation, or inappropriate use of mechanization (e.g., ploughing down a hill slope)',
    'Other',
  ],
  [Category.SEALED_SOILS]: [
    'Urbanization (Construction of buildings and roads)',
    'Agricultural practices (Use of heavy machinery)',
    'Industrial activities (Factories and other industrial sites)',
    'Soil compaction (Soil particles pressed together, reducing pore space)',
    'Paving and concreting (Covering soil with impermeable materials)',
    'Natural processes (e.g., crust formation)',
    'Other',
  ],
  [Category.DEGRADATION]: [
    'Erosion (Loss of topsoil)',
    'Contamination (e.g., chemicals, pollutants)',
    'Loss of nutrients (Depletion of essential soil nutrients)',
    'Overuse of soil (Intensive farming or other activities)',
    'Deforestation (Removal of trees that protect soil)',
    'Climate change (Long-term changes in weather patterns)',
    'Overgrazing (Excessive grazing by livestock)',
    'Other',
  ],
  [Category.LOSS_OF_ORGANIC_MATTER]: [
    'Intensive agriculture (Frequent cropping and tillage)',
    'Deforestation (Removal of trees and vegetation)',
    'Overgrazing (Excessive grazing by livestock)',
    'Soil erosion (Loss of topsoil containing organic matter)',
    'Climate change (Changes in temperature and precipitation)',
    'Poor land management (Inadequate soil conservation practices)',
    'Other',
  ],
  [Category.PH]: [
    'Acidic (e.g., presence of blueberries, azaleas)',
    'Slightly acidic (e.g., presence of ferns, rhododendrons)',
    'Neutral (e.g., presence of clover, dandelions)',
    'Slightly alkaline (e.g., presence of lavender, yarrow)',
    'Alkaline (e.g., presence of sagebrush, saltbush)',
    'Not sure (Unsure about the types of plants or their indication)',
    'Other',
  ],
  [Category.BIODIVERSITY]: [
    'Agricultural practices (Use of pesticides, monoculture)',
    'Urbanization (Loss of natural habitats)',
    'Pollution (Contaminants affecting soil life)',
    'Climate change (Changes in temperature and precipitation)',
    'Deforestation (Loss of trees and vegetation)',
    'Natural soil conditions (Inherent soil properties)',
    'Other',
  ],
};
